name: Prepare release
on:
  push:
    branches:
    - 'release/**'

jobs:
  job_compute_release_name:
    runs-on: ubuntu-18.04
    container:
      image: docker://alpine/git:v2.24.3
    outputs:
      release_name: ${{ steps.step_compute_release_name.outputs.release_name }}
    steps:
      - id: step_compute_release_name
        env:
          GIT_REF: ${{ github.ref }}
        run: |
          release_name=${GIT_REF#refs/heads/release/}
          echo "Release name=$release_name"
          echo "::set-output name=release_name::$release_name"

  job_create_prepare_release_pr:
    needs: [job_compute_release_name]
    runs-on: ubuntu-18.04
    container:
      image: docker://alpine/git:v2.24.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog file
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }} --since_tag 3.5.0 --future-release ${{ needs.job_compute_release_name.outputs.release_name }}

      - name: Commit changes
        uses: actions-x/commit@v1
        with:
          message: Add changelog

      - name: Create pr
        id: step_create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "master"
          pr_title: "Prepare release ${{ needs.job_compute_release_name.outputs.release_name }}"
