name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0.6', '3.1.4', '3.2.0']

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run linter
        run: bundle exec rubocop
      - run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS" > account_secret.json'
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: Run tests
        run: bundle exec rake test
        env:
          GOOGLE_APPLICATION_CREDENTIALS: 'account_secret.json'
