name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1.4', '3.2.0', '3.3.5']

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run linter
        run: bundle exec rubocop --lint
      - name: Run tests
        run: bundle exec rake test
      - run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS" > account_secret.json'
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: Run private google sheet tests
        if: matrix.ruby == '3.3.5' # Limit execution on latest ruby version to prevent reaching rate limits
        run: bundle exec rake test_private_google_sheet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: 'account_secret.json'
